[package]
name = "gix-ops"
edition = "2021"
version = "0.2.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.32.0"
anyhow = "1.0.89"
reqwest = "0.12.7"
# wasi = "0.13.1+wasi-0.2.0"
